# A unique identifier for the workspace
workspace_name: defaults

# Kubernetes resources that need to be configured for the scaler to be
# able to manage the cluster. If any of the provided resources don't
# exist, the scaler will attempt to create them. If this fails, you may
# not have the required permissions and will have to request them to be
# created by your cluster administrator.
provider:
    type: kubernetes

    # Exposing external IP addresses for pods isn't currently supported.
    use_internal_ips: true

    # Namespace to use for all resources created.
    namespace: cloudtik

    # ServiceAccount created by the scaler for the head node pod that it
    # runs in. If this field isn't provided, the head pod config below must
    # contain a user-created service account with the proper permissions.
    scaler_service_account:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
            name: cloudtik_scaler

    # Role created by the scaler for the head node pod that it runs in.
    # If this field isn't provided, the role referenced in
    # scaler_role_binding must exist and have at least these permissions.
    scaler_role:
        kind: Role
        apiVersion: rbac.authorization.k8s.io/v1
        metadata:
            name: cloudtik_scaler
        rules:
        - apiGroups: [""]
          resources: ["pods", "pods/status", "pods/exec"]
          verbs: ["get", "watch", "list", "create", "delete", "patch"]

    # RoleBinding created by the scaler for the head node pod that it runs
    # in. If this field isn't provided, the head pod config below must contain
    # a user-created service account with the proper permissions.
    scaler_role_binding:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
            name: cloudtik_scaler
        subjects:
        - kind: ServiceAccount
          name: cloudtik_scaler
        roleRef:
            kind: Role
            name: cloudtik_scaler
            apiGroup: rbac.authorization.k8s.io

    services:
      # Service that maps to the head node of the cluster.
      - apiVersion: v1
        kind: Service
        metadata:
            # NOTE: If you're running multiple clusters with services
            # on one Kubernetes cluster, they must have unique service
            # names.
            name: example-cluster-cloudtik-head
        spec:
            # This selector must match the head node pod's selector below.
            selector:
                component: example-cluster-cloudtik-head
            ports:
                - name: client
                  protocol: TCP
                  port: 10001
                  targetPort: 10001
                - name: dashboard
                  protocol: TCP
                  port: 8265
                  targetPort: 8265
