name: runtime

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - ccache
  - cmake
  - cxx-compiler
  - jupyterlab
  - mpi4py
  - openmpi
  - pip
  - pip:
    - tensorflow==2.4.*
    - -r requirements.txt
  - python=3.8
  - pytorch=1.7
  - tensorboard=2.4
  - torchaudio
  - torchvision
